services:
  - type: web
    name: koffee-karma
    env: python
    plan: free
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt"
    startCommand: python app.py
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false