services:
  - type: web
    name: coffee-karma
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false